<?php
/**
 * SkillRepositoryPdo: PDO-based implementation of SkillRepositoryInterface.
 *
 * @author Mikhail Deynekin <mikhail@deynekin.com>
 * @copyright 2026 https://Deynekin.com
 * @version 1.0.0
 * @since 2026-04-28
 */

declare(strict_types=1);

namespace App\Infrastructure\Persistence\Council;

use App\Domain\Council\Skill;
use App\Domain\Council\SkillRepositoryInterface;
use DateTimeImmutable;
use JsonException;
use PDO;
use PDOException;
use Psr\Log\LoggerInterface;

/**
 * PDO-backed Skill repository.
 */
final readonly class SkillRepositoryPdo implements SkillRepositoryInterface
{
    public function __construct(
        private PDO $pdo,
        private LoggerInterface $logger
    ) {}

    public function findById(int $id): ?Skill
    {
        $sql = 'SELECT id, name, description, roles, consensus, tags, created_at, updated_at
                FROM skills
                WHERE id = :id AND is_active = 1
                LIMIT 1';

        try {
            $stmt = $this->pdo->prepare($sql);
            $stmt->bindValue(':id', $id, PDO::PARAM_INT);
            $stmt->execute();
            $row = $stmt->fetch(PDO::FETCH_ASSOC);

            if ($row === false) {
                return null;
            }

            return $this->hydrateSkill($row);
        } catch (PDOException|JsonException $e) {
            $this->logger->error('SkillRepositoryPdo::findById failed', [
                'id'    => $id,
                'error' => $e->getMessage(),
            ]);

            return null;
        }
    }

    public function findByName(string $name): ?Skill
    {
        $sql = 'SELECT id, name, description, roles, consensus, tags, created_at, updated_at
                FROM skills
                WHERE name = :name AND is_active = 1
                LIMIT 1';

        try {
            $stmt = $this->pdo->prepare($sql);
            $stmt->bindValue(':name', $name, PDO::PARAM_STR);
            $stmt->execute();
            $row = $stmt->fetch(PDO::FETCH_ASSOC);

            if ($row === false) {
                return null;
            }

            return $this->hydrateSkill($row);
        } catch (PDOException|JsonException $e) {
            $this->logger->error('SkillRepositoryPdo::findByName failed', [
                'name'  => $name,
                'error' => $e->getMessage(),
            ]);

            return null;
        }
    }

    /**
     * @return Skill[]
     */
    public function findAll(): array
    {
        $sql = 'SELECT id, name, description, roles, consensus, tags, created_at, updated_at
                FROM skills
                WHERE is_active = 1
                ORDER BY created_at DESC';

        try {
            $stmt = $this->pdo->query($sql);
            $rows = $stmt->fetchAll(PDO::FETCH_ASSOC) ?: [];

            $skills = [];
            foreach ($rows as $row) {
                $skills[] = $this->hydrateSkill($row);
            }

            return $skills;
        } catch (PDOException|JsonException $e) {
            $this->logger->error('SkillRepositoryPdo::findAll failed', [
                'error' => $e->getMessage(),
            ]);

            return [];
        }
    }

    public function save(Skill $skill, bool $isAutoGenerated = true): Skill
    {
        $rolesJson = json_encode($skill->getRoles(), JSON_THROW_ON_ERROR);
        $tagsJson  = json_encode($skill->getTags(), JSON_THROW_ON_ERROR);

        if ($skill->getId() === 0) {
            $sql = 'INSERT INTO skills (
                        name, description, roles, consensus, tags,
                        is_auto_generated, is_active, version, created_by, updated_by, created_at
                    ) VALUES (
                        :name, :description, :roles, :consensus, :tags,
                        :is_auto_generated, 1, 1, NULL, NULL, NOW()
                    )';

            try {
                $stmt = $this->pdo->prepare($sql);
                $stmt->bindValue(':name', $skill->getName(), PDO::PARAM_STR);
                $stmt->bindValue(':description', $skill->getDescription(), PDO::PARAM_STR);
                $stmt->bindValue(':roles', $rolesJson, PDO::PARAM_STR);
                $stmt->bindValue(':consensus', $skill->getConsensus(), PDO::PARAM_STR);
                $stmt->bindValue(':tags', $tagsJson, PDO::PARAM_STR);
                $stmt->bindValue(':is_auto_generated', $isAutoGenerated ? 1 : 0, PDO::PARAM_INT);

                $stmt->execute();
                $id = (int) $this->pdo->lastInsertId();

                return new Skill(
                    id: $id,
                    name: $skill->getName(),
                    description: $skill->getDescription(),
                    roles: $skill->getRoles(),
                    consensus: $skill->getConsensus(),
                    tags: $skill->getTags(),
                    createdAt: new DateTimeImmutable('now'),
                    updatedAt: null,
                );
            } catch (PDOException $e) {
                $this->logger->error('SkillRepositoryPdo::save insert failed', [
                    'name'  => $skill->getName(),
                    'error' => $e->getMessage(),
                ]);

                throw $e;
            }
        }

        $sql = 'UPDATE skills
                SET name = :name,
                    description = :description,
                    roles = :roles,
                    consensus = :consensus,
                    tags = :tags,
                    updated_at = NOW()
                WHERE id = :id';

        try {
            $stmt = $this->pdo->prepare($sql);
            $stmt->bindValue(':id', $skill->getId(), PDO::PARAM_INT);
            $stmt->bindValue(':name', $skill->getName(), PDO::PARAM_STR);
            $stmt->bindValue(':description', $skill->getDescription(), PDO::PARAM_STR);
            $stmt->bindValue(':roles', $rolesJson, PDO::PARAM_STR);
            $stmt->bindValue(':consensus', $skill->getConsensus(), PDO::PARAM_STR);
            $stmt->bindValue(':tags', $tagsJson, PDO::PARAM_STR);
            $stmt->execute();

            return new Skill(
                id: $skill->getId(),
                name: $skill->getName(),
                description: $skill->getDescription(),
                roles: $skill->getRoles(),
                consensus: $skill->getConsensus(),
                tags: $skill->getTags(),
                createdAt: $skill->getCreatedAt(),
                updatedAt: new DateTimeImmutable('now'),
            );
        } catch (PDOException $e) {
            $this->logger->error('SkillRepositoryPdo::save update failed', [
                'id'    => $skill->getId(),
                'error' => $e->getMessage(),
            ]);

            throw $e;
        }
    }

    public function delete(int $id): bool
    {
        $sql = 'UPDATE skills
                SET is_active = 0, updated_at = NOW()
                WHERE id = :id';

        try {
            $stmt = $this->pdo->prepare($sql);
            $stmt->bindValue(':id', $id, PDO::PARAM_INT);
            $stmt->execute();

            return $stmt->rowCount() > 0;
        } catch (PDOException $e) {
            $this->logger->error('SkillRepositoryPdo::delete failed', [
                'id'    => $id,
                'error' => $e->getMessage(),
            ]);

            return false;
        }
    }

    public function count(): int
    {
        $sql = 'SELECT COUNT(*) AS cnt FROM skills WHERE is_active = 1';

        try {
            $stmt = $this->pdo->query($sql);
            $row = $stmt->fetch(PDO::FETCH_ASSOC);

            return (int) ($row['cnt'] ?? 0);
        } catch (PDOException $e) {
            $this->logger->error('SkillRepositoryPdo::count failed', [
                'error' => $e->getMessage(),
            ]);

            return 0;
        }
    }

    /**
     * @param array<string,mixed> $row
     */
    private function hydrateSkill(array $row): Skill
    {
        $roles = [];
        $tags  = [];

        if (isset($row['roles'])) {
            $decoded = json_decode((string) $row['roles'], true, 512, JSON_THROW_ON_ERROR);
            $roles = is_array($decoded) ? $decoded : [];
        }

        if (isset($row['tags'])) {
            $decoded = json_decode((string) $row['tags'], true, 512, JSON_THROW_ON_ERROR);
            $tags = is_array($decoded) ? $decoded : [];
        }

        $createdAt = new DateTimeImmutable((string) $row['created_at']);
        $updatedAt = $row['updated_at'] !== null ? new DateTimeImmutable((string) $row['updated_at']) : null;

        return new Skill(
            id: (int) $row['id'],
            name: (string) $row['name'],
            description: (string) $row['description'],
            roles: $roles,
            consensus: (string) $row['consensus'],
            tags: $tags,
            createdAt: $createdAt,
            updatedAt: $updatedAt,
        );
    }
}
