<?php
/**
 * SkillRepositoryInterface: Contract for SKILL persistence operations.
 *
 * @author Mikhail Deynekin <mikhail@deynekin.com>
 * @copyright 2026 https://Deynekin.com
 * @version 1.0.0
 * @since 2026-04-28
 */

declare(strict_types=1);

namespace App\Domain\Council;

/**
 * Defines the persistence contract for SKILL entities.
 */
interface SkillRepositoryInterface
{
    public function findById(int $id): ?Skill;

    public function findByName(string $name): ?Skill;

    /**
     * @return Skill[]
     */
    public function findAll(): array;

    /**
     * Persist or update a SKILL.
     *
     * @param bool $isAutoGenerated Indicates whether the SKILL was auto-generated by LLM
     */
    public function save(Skill $skill, bool $isAutoGenerated = true): Skill;

    public function delete(int $id): bool;

    public function count(): int;
}
