<?php
/**
 * SkillAutoCreator: Automatic Skill generation via LLM when no existing Skill matches.
 *
 * @author Mikhail Deynekin <mikhail@deynekin.com>
 * @copyright 2026 https://Deynekin.com
 * @version 2.0.0
 * @since 2026-04-27
 */

declare(strict_types=1);

namespace App\Application\Council;

use App\Domain\Council\Skill;
use App\Domain\Council\SkillRepositoryInterface;
use App\Infrastructure\BothubChat\BothubClient;
use DateTimeImmutable;
use JsonException;
use Psr\Log\LoggerInterface;
use RuntimeException;
use Throwable;

/**
 * Senior-level implementation of automatic Skill generation using LLM.
 */
readonly final class SkillAutoCreator
{
    private const MODEL = 'gpt-4o';

    public function __construct(
        private BothubClient $bothubClient,
        private SkillRepositoryInterface $skillRepository,
        private SkillSearch $skillSearch,
        private LoggerInterface $logger
    ) {}

    /**
     * Create a new SKILL from a user query using LLM.
     *
     * On failure, falls back to seeding the default consensus SKILL.
     */
    public function createFromQuery(string $userQuery, ?int $sessionId = null): Skill
    {
        $userQuery = trim($userQuery);

        $this->logger->info('SkillAutoCreator: creating Skill from query', [
            'session_id'    => $sessionId,
            'query_preview' => mb_substr($userQuery, 0, 160),
        ]);

        if ($userQuery === '') {
            $this->logger->warning('SkillAutoCreator: empty user query, using default consensus SKILL', [
                'session_id' => $sessionId,
            ]);

            return $this->seedDefaultConsensusSkill();
        }

        try {
            $systemPrompt = $this->buildSystemPromptForArbitrarySkill();
            $userPrompt   = $this->buildUserPromptForArbitrarySkill($userQuery);

            $response = $this->bothubClient->createChatCompletion(
                model: self::MODEL,
                messages: [
                    ['role' => 'system', 'content' => $systemPrompt],
                    ['role' => 'user',   'content' => $userPrompt],
                ],
                options: [
                    'temperature' => 0.4,
                    'max_tokens'  => 2000,
                ]
            );

            $content = $response['choices'][0]['message']['content'] ?? null;
            if (!is_string($content) || trim($content) === '') {
                throw new RuntimeException('LLM response has no content');
            }

            try {
                /** @var array<string,mixed> $data */
                $data = json_decode($content, true, 512, JSON_THROW_ON_ERROR);
            } catch (JsonException $e) {
                throw new RuntimeException('LLM response is not valid JSON: ' . $e->getMessage(), 0, $e);
            }

            $skill = $this->createSkillFromArray($data, isAutoGenerated: true);

            $this->logger->info('SkillAutoCreator: Skill created from query via LLM', [
                'session_id' => $sessionId,
                'skill_id'   => $skill->getId(),
                'name'       => $skill->getName(),
            ]);

            return $skill;
        } catch (Throwable $e) {
            $this->logger->error('SkillAutoCreator: createFromQuery failed, falling back to default SKILL', [
                'session_id' => $sessionId,
                'error'      => $e->getMessage(),
            ]);

            return $this->seedDefaultConsensusSkill();
        }
    }

    /**
     * Seed a default, general-purpose consensus SKILL.
     *
     * Tries LLM-first, then falls back to a canonical built-in JSON definition.
     */
    public function seedDefaultConsensusSkill(): Skill
    {
        try {
            $skill = $this->generateDefaultSkillViaLlm();
            $this->logger->info('SkillAutoCreator: default consensus SKILL generated via LLM', [
                'skill_name' => $skill->getName(),
            ]);

            return $skill;
        } catch (Throwable $e) {
            $this->logger->warning('SkillAutoCreator: LLM generation failed, falling back to built-in default SKILL', [
                'error' => $e->getMessage(),
            ]);
        }

        $fallbackJson = $this->getDefaultSkillJson();

        try {
            /** @var array<string,mixed> $data */
            $data = json_decode($fallbackJson, true, 512, JSON_THROW_ON_ERROR);
        } catch (JsonException $e) {
            $this->logger->error('SkillAutoCreator: fallback JSON for default SKILL is invalid', [
                'error' => $e->getMessage(),
            ]);
            throw $e;
        }

        return $this->createSkillFromArray($data, isAutoGenerated: false);
    }

    /**
     * Generate the default consensus SKILL via LLM using an internal spec.
     */
    private function generateDefaultSkillViaLlm(): Skill
    {
        $systemPrompt = 'You are a system designer tasked with defining a general-purpose ' .
            'deliberative SKILL for a multi-agent council. You MUST output a SINGLE JSON object ' .
            'with the following structure: ' .
            '{"name": string (snake_case), "description": string, "roles": [role...], ' .
            '"consensus": {"strategy": "majority_vote"|"weighted_average"|"synthesis", "parameters": object}, ' .
            '"tags": [string...], "meta": object}. ' .
            'Each role must have: id, name, purpose, style, constraints, system_prompt, weight. ' .
            'Do NOT include any text before or after the JSON. Do NOT wrap JSON in code fences.';

        $userPrompt = 'Define a default, general-purpose "general_consensus_council" SKILL that: ' .
            '1) analyzes complex user queries from multiple expert perspectives, ' .
            '2) critiques its own reasoning, ' .
            '3) produces a synthesized, well-argued final answer with explicit trade-offs and uncertainties. ' .
            'Use exactly 4 roles with the following identities: ' .
            '(1) Analytical Expert, (2) Critical Reviewer, (3) User Advocate, (4) Synthesis Arbiter. ' .
            'Make sure the "name" field is "general_consensus_council" in snake_case.';

        $response = $this->bothubClient->createChatCompletion(
            model: self::MODEL,
            messages: [
                ['role' => 'system', 'content' => $systemPrompt],
                ['role' => 'user',   'content' => $userPrompt],
            ],
            options: [
                'temperature' => 0.3,
                'max_tokens'  => 2000,
            ]
        );

        $content = $response['choices'][0]['message']['content'] ?? null;
        if (!is_string($content) || trim($content) === '') {
            throw new RuntimeException('LLM response has no content');
        }

        try {
            /** @var array<string,mixed> $data */
            $data = json_decode($content, true, 512, JSON_THROW_ON_ERROR);
        } catch (JsonException $e) {
            throw new RuntimeException('LLM response is not valid JSON: ' . $e->getMessage(), 0, $e);
        }

        return $this->createSkillFromArray($data, isAutoGenerated: true);
    }

    /**
     * Build a Skill entity from decoded JSON and persist + index it.
     *
     * @param array<string,mixed> $data
     */
    private function createSkillFromArray(array $data, bool $isAutoGenerated): Skill
    {
        $name        = (string) ($data['name'] ?? '');
        $description = (string) ($data['description'] ?? '');
        $roles       = (array)  ($data['roles'] ?? []);
        $tags        = (array)  ($data['tags'] ?? []);

        $consensusRaw = $data['consensus']['strategy'] ?? ($data['consensus'] ?? 'synthesis');
        $consensus    = is_string($consensusRaw) ? $consensusRaw : 'synthesis';

        if ($name === '' || $description === '') {
            throw new RuntimeException('SKILL JSON must contain non-empty name and description');
        }

        $skill = new Skill(
            id: 0,
            name: $name,
            description: $description,
            roles: $roles,
            consensus: $consensus,
            tags: $tags,
            createdAt: new DateTimeImmutable('now'),
            updatedAt: null,
        );

        $saved = $this->skillRepository->save($skill, $isAutoGenerated);
        $this->skillSearch->indexSkill($saved);

        return $saved;
    }

    /**
     * Canonical fallback JSON for the default consensus SKILL.
     */
    private function getDefaultSkillJson(): string
    {
        return json_encode([
            'name' => 'general_consensus_council',
            'description' => 'General-purpose deliberative council that analyzes complex user queries from multiple expert perspectives, critiques its own reasoning, and produces a synthesized, well-argued final answer with explicit trade-offs and uncertainties.',
            'roles' => [
                [
                    'id' => 'analyst',
                    'name' => 'Analytical Expert',
                    'purpose' => 'Decompose the user\'s query into subproblems, identify key variables, constraints, and possible solution strategies.',
                    'style' => [
                        'tone' => 'neutral_technical',
                        'verbosity' => 'medium',
                        'structure' => 'numbered_steps',
                    ],
                    'constraints' => [
                        'Always separate facts, assumptions, and open questions.',
                        'Do not jump to recommendations; focus on understanding the problem space.',
                        'Explicitly list alternative approaches when possible.',
                    ],
                    'system_prompt' => 'You are the Analytical Expert in a multi-agent council. Your job is to deeply understand the user\'s query, decompose it into subproblems, identify key variables and constraints, and outline possible solution strategies without committing to a final recommendation. Always structure your output as: (1) Problem restatement, (2) Decomposition, (3) Key variables and constraints, (4) Potential approaches.',
                    'weight' => 1.0,
                ],
                [
                    'id' => 'critic',
                    'name' => 'Critical Reviewer',
                    'purpose' => 'Stress-test the preliminary reasoning for logical gaps, hidden assumptions, and potential failure modes.',
                    'style' => [
                        'tone' => 'skeptical_but_constructive',
                        'verbosity' => 'medium',
                        'structure' => 'bullets',
                    ],
                    'constraints' => [
                        'Do not simply repeat previous reasoning.',
                        'Focus on identifying weaknesses, blind spots, and edge cases.',
                        'Suggest concrete improvements or additional checks instead of vague criticisms.',
                    ],
                    'system_prompt' => 'You are the Critical Reviewer in a multi-agent council. Your job is to stress-test the current reasoning: find logical gaps, hidden assumptions, risks, and edge cases that might invalidate the conclusion. Be skeptical but constructive. Structure your answer as: (1) Key concerns, (2) Assumptions that need validation, (3) Worst-case scenarios, (4) Suggestions for strengthening the reasoning.',
                    'weight' => 0.8,
                ],
                [
                    'id' => 'user_advocate',
                    'name' => 'User Advocate',
                    'purpose' => 'Reframe the analysis in terms of the user\'s goals, constraints, and risk tolerance, emphasizing clarity and practicality.',
                    'style' => [
                        'tone' => 'empathetic_pragmatic',
                        'verbosity' => 'medium',
                        'structure' => 'short_paragraphs',
                    ],
                    'constraints' => [
                        'Avoid jargon unless it is briefly explained.',
                        'Always tie recommendations back to the user\'s stated goals and constraints.',
                        'Highlight trade-offs and residual uncertainty in plain language.',
                    ],
                    'system_prompt' => 'You are the User Advocate in a multi-agent council. Your job is to translate technical analysis into clear, practical guidance aligned with the user\'s goals and constraints. Focus on what the user cares about: outcomes, risks, effort, and time. Explain trade-offs and residual uncertainty in plain language.',
                    'weight' => 1.0,
                ],
                [
                    'id' => 'arbiter',
                    'name' => 'Synthesis Arbiter',
                    'purpose' => 'Integrate all previous perspectives into a coherent, well-justified final answer with explicit trade-offs and rationale.',
                    'style' => [
                        'tone' => 'authoritative_but_cautious',
                        'verbosity' => 'high',
                        'structure' => 'numbered_steps',
                    ],
                    'constraints' => [
                        'Explicitly reference points of agreement and disagreement between roles.',
                        'Make the reasoning traceable from premises to conclusion.',
                        'Do not hide uncertainty; quantify confidence qualitatively (e.g. low/medium/high).',
                    ],
                    'system_prompt' => 'You are the Synthesis Arbiter in a multi-agent council. You receive inputs from multiple expert roles (analysis, critique, user perspective) and must integrate them into a single, coherent answer. Your output must: (1) summarize the problem, (2) highlight key insights from each role, (3) present a clear recommendation or set of options, (4) explain trade-offs, and (5) state remaining uncertainties and confidence level.',
                    'weight' => 1.2,
                ],
            ],
            'consensus' => [
                'strategy' => 'synthesis',
                'parameters' => [
                    'min_roles' => 3,
                    'max_roles' => 4,
                    'require_critic' => true,
                    'confidence_labels' => ['low', 'medium', 'high'],
                ],
            ],
            'tags' => [
                'general',
                'consensus',
                'council',
                'multi_agent',
                'analysis',
                'decision_support',
            ],
            'meta' => [
                'version' => 1,
                'author' => 'system',
                'origin' => 'seed_default',
                'intended_use' => 'general_decision_support',
                'language' => 'en',
                'created_at' => (new DateTimeImmutable('now'))->format(DATE_ATOM),
            ],
        ], JSON_THROW_ON_ERROR);
    }

    /**
     * System prompt for arbitrary Skill creation from user query.
     */
    private function buildSystemPromptForArbitrarySkill(): string
    {
        return 'You are an expert system designer for a multi-agent AI council engine. ' .
            'Generate a JSON object that defines a SKILL for handling the user\'s query. ' .
            'Output MUST be valid JSON only, with no markdown or surrounding text. ' .
            'The JSON must contain at least: name (snake_case), description, roles (1-10), ' .
            'consensus ("majority_vote"|"weighted_average"|"synthesis"), and tags (array of strings). ' .
            'Each role should have: id, name, purpose, system_prompt, and may have style, constraints, and weight.';
    }

    /**
     * User prompt for arbitrary Skill creation from user query.
     */
    private function buildUserPromptForArbitrarySkill(string $userQuery): string
    {
        return 'User query: ' . $userQuery . '\n' .
            'Define a SKILL that is best suited to address this query. ' .
            'Make the name short and descriptive in snake_case, and choose roles that naturally decompose the problem.';
    }
}
